# This is a sample file, for detailed reference see: https://rudderlabs.github.io/pywht/
models:
  - name: user_id_stitcher
    model_type: id_stitcher
    model_spec:
      entity_key: user
      edge_sources:
        - from: inputs/rsIdentifies
        - from: inputs/rsTracks
  - name: users_with_valid_email
    model_type: entity_cohort
    model_spec:
      extends: user/all
      filter_pipeline:
        - type: exclude
          value: "{{ user.Var('id_email_em2_count')}} >= 1"
      feature_views:
        name: users_with_valid_email_feature_view
  - name: users_with_invalid_email
    model_type: entity_cohort
    model_spec:
      extends: user/all
      filter_pipeline:
        - type: exclude
          value: "{{ user.Var('id_email_em2_count')}} < 1"
      feature_views:
        name: users_with_invalid_email_feature_view
var_groups:
  - name: default_vars
    entity_key: user
    vars:
      - input_var:
          name: CONTEXT_PAGE_URL_IV
          select: CONTEXT_PAGE_URL
          from: inputs/rsTracks
      - entity_var:
          name: CONTEXT_PAGE_URL_EV
          select: any_value({{rsTracks.Var("CONTEXT_PAGE_URL_IV")}})
          from: inputs/rsTracks
      - entity_var:
          name: first_seen
          select: min(cast(timestamp as date))
          from: inputs/rsTracks
          is_feature: false
      - entity_var:
          name: last_seen
          select: max(cast(timestamp as date))
          from: inputs/rsTracks
          is_feature: false
      - entity_var:
          name: user_lifespan
          select: '{{user.Var("last_seen")}} - {{user.Var("first_seen")}}'
          description: Life Time Value of a customer
      - entity_var:
          name: days_active
          select: count(distinct cast(timestamp as date))
          from: inputs/rsTracks
          description: No. of days a customer was active
      - entity_var:
          name: id_email_em2_count
          select: sum(case when other_id_type = 'email' and other_id = 'em2@e.com' then 1 else 0 end)
          from: models/user_id_stitcher
          description: Count of em2 emails
      - entity_var:
          name: hcpcs_code
          select: ARRAY_DISTINCT(ARRAY_FLATTEN(ARRAY_AGG(HCPCS_CODES)))
          from: models/sampledata
          is_feature: true 
  # - name: users_with_valid_email_cohort_vars
  #   entity_cohort: models/users_with_valid_email
  #   vars:
  #     - entity_var:
  #         name: first_seen
  #         select: '{{user.Var("first_seen")}}'
  # - name: users_with_invalid_email_cohort_vars
  #   entity_cohort: models/users_with_invalid_email
  #   vars:
  #     - entity_var:
  #         name: first_seen
  #         select: '{{user.Var("first_seen")}}'
          